/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 E:\testProject\liveModel\public\uploads\models\glb\shiba789_1733374803939.glb -t -o E:\testProject\liveModel\src\models\shiba789_1733374803939.tsx 
Author: zixisun02 (https://sketchfab.com/zixisun51)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiba-faef9fe5ace445e7b2989d1c1ece361c
Title: Shiba
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Group18985_default_0: THREE.Mesh
    Box002_default_0: THREE.Mesh
    Object001_default_0: THREE.Mesh
  }
  materials: {
    ['default']: THREE.MeshBasicMaterial
  }
}

export function Model_1733374803939(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/uploads/models/glb/shiba789_1733374803939.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Group18985_default_0.geometry} material={materials['default']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Box002_default_0.geometry} material={materials['default']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object001_default_0.geometry} material={materials['default']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/uploads/models/glb/shiba789_1733374803939.glb')
