/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 E:\testProject\liveModel\public\uploads\models\Wolf-Blender-2.82a_1733109683962.glb -t -o E:\testProject\liveModel\src\models\Wolf-Blender-2.82a_1733109683962.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = '01_Run_Armature_0' | '02_walk_Armature_0' | '03_creep_Armature_0' | '04_Idle_Armature_0' | '05_site_Armature_0'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Wolf1_Material__wolf_col_tga_0: THREE.SkinnedMesh
    Wolf2_fur__fella3_jpg_001_0: THREE.SkinnedMesh
    Wolf3_claws_0: THREE.SkinnedMesh
    Wolf3_eyes_0: THREE.SkinnedMesh
    Wolf3_teeth: THREE.SkinnedMesh
    Circle: THREE.Mesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Wolf_1: THREE.MeshStandardMaterial
    Wolf_Fur: THREE.MeshStandardMaterial
    Wolf_claws: THREE.MeshStandardMaterial
    ['Wolf Eyes']: THREE.MeshStandardMaterial
    ['Wolf Teeth']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model_1733109683962(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/uploads/models/glb/Wolf-Blender-2.82a_1733109683962.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature_0">
          <primitive object={nodes._rootJoint} />
          <skinnedMesh name="Wolf1_Material__wolf_col_tga_0" geometry={nodes.Wolf1_Material__wolf_col_tga_0.geometry} material={materials.Wolf_1} skeleton={nodes.Wolf1_Material__wolf_col_tga_0.skeleton} />
          <skinnedMesh name="Wolf2_fur__fella3_jpg_001_0" geometry={nodes.Wolf2_fur__fella3_jpg_001_0.geometry} material={materials.Wolf_Fur} skeleton={nodes.Wolf2_fur__fella3_jpg_001_0.skeleton} />
          <skinnedMesh name="Wolf3_claws_0" geometry={nodes.Wolf3_claws_0.geometry} material={materials.Wolf_claws} skeleton={nodes.Wolf3_claws_0.skeleton} />
          <skinnedMesh name="Wolf3_eyes_0" geometry={nodes.Wolf3_eyes_0.geometry} material={materials['Wolf Eyes']} skeleton={nodes.Wolf3_eyes_0.skeleton} />
          <skinnedMesh name="Wolf3_teeth" geometry={nodes.Wolf3_teeth.geometry} material={materials['Wolf Teeth']} skeleton={nodes.Wolf3_teeth.skeleton} />
        </group>
        <group name="Sun" position={[0.553, 1.181, 0.892]} rotation={[0.43, -0.322, -0.522]} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.001']} position={[0, -0.011, 0]} scale={0.637} />
      </group>
    </group>
  )
}

useGLTF.preload('/uploads/models/glb/Wolf-Blender-2.82a_1733109683962.glb')
